Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -22,8 +22,9 @@ jobs:
 
     - name: Build project
       run: |
-        make
-        strip ndpresponder
+        chmod +x build.sh
+        ./build.sh
+        strip ndpresponder || echo "Unable to strip binary"
         
     - name: Create artifacts directory
       run: mkdir -p artifacts
